import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.js';
import {MockCRM} from '../src/crm/mock.js';
import {executeTool,confirmAction,safeRecord} from '../src/agent/tools.js';
import {runAgent} from '../src/agent/runner.js';
function fixture(t){const store=new Store(':memory:');t.after(()=>store.close());return {store,crm:new MockCRM(store),session:store.newSession(),config:{llmMode:'demo',bookedStage:'Closed Won - Booking Done',paymentHosts:['pay.example.com']}};}
const lead={fullName:'Sagar Rana',phone:'9000000004',email:'sagar@example.com',city:'Pune',vehicle:'Thar'};
test('lead is created only after confirmation; confirmation replay is idempotent',async t=>{const c=fixture(t);const before=c.store.records('Leads').length;const r=await executeTool('propose_lead',lead,c);assert.equal(r.awaitingConfirmation,true);assert.equal(c.store.records('Leads').length,before);const id=c.session.pending.id;const result=await confirmAction(c,id);assert.equal(result.module,'Leads');assert.equal(c.store.records('Leads').length,before+1);assert.deepEqual(await confirmAction(c,id),result);assert.equal(c.store.records('Leads').length,before+1);});
test('existing lead and invalid details cannot create duplicates',async t=>{const c=fixture(t);assert.ok((await executeTool('propose_lead',{...lead,email:'invalid'},c)).error);assert.equal(c.session.pending,null);const r=await executeTool('propose_lead',{...lead,phone:'9000000001'},c);assert.equal(r.alreadyExists,true);assert.equal(c.session.pending,null);});
test('lookup a deal then update follow-up; arbitrary deal ID is blocked',async t=>{const c=fixture(t);assert.ok((await executeTool('propose_follow_up',{dealId:'deal-priya',preference:'Evenings'},c)).error);const r=await executeTool('find_deal',{identifier:'9000000002'},c);assert.equal(r.records[0].stage,'Test Drive Scheduled');await executeTool('propose_follow_up',{dealId:r.records[0].id,preference:'WhatsApp after 6 PM'},c);await confirmAction(c,c.session.pending.id);assert.equal((await c.crm.get('Deals','deal-priya')).followUp,'WhatsApp after 6 PM');});
test('booking lookup reflects external CRM edits and does not invent VIN/payment',async t=>{const c=fixture(t);let r=await executeTool('find_booking',{identifier:'MAH-9921'},c);assert.equal(r.records[0].allocationStage,'In Transit');assert.equal(r.records[0].vin,null);assert.equal(r.records[0].paymentUrl,null);await c.crm.update('Deals','deal-booking',{allocationStage:'Delivered'});r=await executeTool('find_booking',{identifier:'9000000003'},c);assert.equal(r.records[0].allocationStage,'Delivered');assert.equal((await executeTool('find_deal',{identifier:'9000000003'},c)).records.length,0);});
test('service case links to an existing contact and validates odometer',async t=>{const c=fixture(t);const args={contactId:'contact-arjun',registration:'MH12AB1234',odometer:15000,issue:'Periodic maintenance requested',location:'Pune',serviceType:'Periodic maintenance'};assert.ok((await executeTool('propose_service',args,c)).error);await executeTool('find_contact',{phone:'9000000003'},c);assert.ok((await executeTool('propose_service',{...args,odometer:-1},c)).error);await executeTool('propose_service',args,c);const r=await confirmAction(c,c.session.pending.id);assert.equal(r.record.contactId,'contact-arjun');assert.equal(r.record.status,'New');assert.equal(c.store.records('Cases').length,1);});
test('unknown booking/phone and tools fail safely',async t=>{const c=fixture(t);assert.equal((await executeTool('find_booking',{identifier:'MAH-0000'},c)).records.length,0);assert.ok((await executeTool('find_deal',{identifier:'(x:equals:y)'},c)).error);assert.ok((await executeTool('delete_all',{},c)).error);});
test('session state survives topic switching and reload',async t=>{const c=fixture(t);await runAgent(c,'I am interested in Thar');await runAgent(c,'Check booking MAH-9921');assert.equal(c.session.stage,'booking');await runAgent(c,'I am interested. name: Sagar Rana; phone: 9000000004; email: sagar@example.com; city: Pune');assert.equal(c.session.pending.data.vehicle,'Thar');assert.equal(c.store.session(c.session.token).messages.length,6);assert.equal(c.store.session(c.session.token).pending.kind,'lead');});
test('LLM tool orchestration returns tool results before final reply',async t=>{const c=fixture(t);c.config.llmMode='groq';let n=0;c.provider={complete:async(messages,tools,delta)=>{n++;if(n===1)return {role:'assistant',content:null,tool_calls:[{id:'call_1',type:'function',function:{name:'find_booking',arguments:'{"identifier":"MAH-9921"}'}}]};assert.equal(messages.at(-1).role,'tool');assert.equal(JSON.parse(messages.at(-1).content).records[0].allocationStage,'In Transit');delta('Your vehicle is In Transit.');return {role:'assistant',content:'Your vehicle is In Transit.'};}};assert.equal(await runAgent(c,'Where is MAH-9921?'),'Your vehicle is In Transit.');assert.equal(n,2);assert.equal(c.session.stage,'booking');});
test('payment URLs require HTTPS and exact host allowlist',async t=>{const c=fixture(t);for(const url of ['javascript:alert(1)','https://evil.example.com','https://pay.example.com.evil.com','http://pay.example.com'])assert.equal(safeRecord(c.config,{paymentUrl:url}).paymentUrl,null);assert.equal(safeRecord(c.config,{paymentUrl:'https://pay.example.com/order/1'}).paymentUrl,'https://pay.example.com/order/1');});
test('uncertain CRM writes cannot silently repeat',async t=>{const c=fixture(t);await executeTool('propose_lead',lead,c);const id=c.session.pending.id;c.crm.create=async()=>{const e=new Error('timeout');e.code='WRITE_UNCERTAIN';throw e;};await assert.rejects(confirmAction(c,id));assert.equal(c.store.operation(id).state,'uncertain');await assert.rejects(confirmAction(c,id),/uncertain earlier outcome/);});
test('another session cannot confirm a known action ID',async t=>{const c=fixture(t);await executeTool('propose_lead',lead,c);const id=c.session.pending.id;await assert.rejects(confirmAction({...c,session:c.store.newSession()},id),/not found/);await confirmAction(c,id);await assert.rejects(confirmAction({...c,session:c.store.newSession()},id),/not found/);});
