import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,initSession,forgetSession,stream} from './api';
import './styles.css';
const stages=[['discovery','01','Discover a vehicle','Models, features & test drives'],['pipeline','02','Your next step','Deals, quotes & follow-ups'],['booking','03','Track your booking','Allocation & delivery updates'],['service','04','Care for your vehicle','Service requests & support']];
const prompts={discovery:'I am interested in Thar. Tell me about its features and price.',pipeline:'Check my existing deal. My phone is 9000000002.',booking:'What is the delivery status of booking MAH-9921?',service:'I need periodic maintenance. My phone is 9000000003.'};
const readable=key=>key.replace(/([A-Z])/g,' $1').replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
function App(){
 const [health,setHealth]=useState(null),[session,setSession]=useState({messages:[],stage:'discovery',pending:null}),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[live,setLive]=useState(''),[status,setStatus]=useState(''),[records,setRecords]=useState([]),[checked,setChecked]=useState(null),[ready,setReady]=useState(false),[syncState,setSyncState]=useState('Connecting');
 const bottom=useRef(null),input=useRef(null),snapshotBusy=useRef(false);
 async function load(){setSession(await api('/session'));}
 async function snapshot(){if(snapshotBusy.current)return;snapshotBusy.current=true;try{const result=await api('/crm/snapshot');setRecords(result.records);setChecked(result.checkedAt);}catch(e){setError(e.message);}finally{snapshotBusy.current=false;}}
 useEffect(()=>{let active=true;Promise.all([api('/health'),initSession()]).then(([h,s])=>{if(active){setHealth(h);setSession(s);setReady(true);}}).catch(e=>setError(e.message));return()=>{active=false;};},[]);
 useEffect(()=>{if(!ready)return;const controller=new AbortController();let retry,timer;let stopped=false;
  const connect=()=>{setSyncState('Connecting');stream('/events',{signal:controller.signal},(event)=>{if(event==='connected')setSyncState('Connected');if(event==='crm_changed'){setStatus('CRM update received');snapshot();}}).then(()=>{if(!stopped){setSyncState('Reconnecting');retry=setTimeout(connect,3000);}}).catch(e=>{if(!stopped){setSyncState('Reconnecting');retry=setTimeout(connect,3000);}});};
  connect();snapshot();if(health?.pollMs>0)timer=setInterval(()=>{if(!document.hidden)snapshot();},Math.max(health.pollMs,10000));
  return()=>{stopped=true;controller.abort();clearTimeout(retry);clearInterval(timer);};
 },[ready,health]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[session.messages,live,session.pending]);
 async function send(event,message=draft){event?.preventDefault();if(!message.trim()||busy||!ready)return;setBusy(true);setError('');setLive('');setDraft('');setStatus('Understanding your request…');setSession(s=>({...s,messages:[...s.messages,{role:'user',content:message}]}));
  try{await stream('/chat',{method:'POST',body:JSON.stringify({message})},(event,data)=>{if(event==='delta')setLive(v=>v+data.text);if(event==='status')setStatus(data.message);if(event==='error')setError(data.error);});await load();await snapshot();}catch(e){setError(e.message);await load().catch(()=>{});}finally{setBusy(false);setLive('');setStatus('');input.current?.focus();}
 }
 async function act(action){setBusy(true);setError('');try{const result=await api(`/actions/${session.pending.id}/${action}`,{method:'POST'});await load();await snapshot();setStatus(result?.message || 'Change cancelled');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function reset(){if(busy)return;setReady(false);forgetSession();setRecords([]);setError('');try{setSession(await initSession());setReady(true);}catch(e){setError(e.message);}}
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="ABC Automotive home"><span className="brand-icon">A</span><span>ABC<span className="brand-sub">AUTOMOTIVE</span></span></a><div className="nav-label">YOUR OWNERSHIP JOURNEY</div><nav>{stages.map(([key,n,title,sub])=><button key={key} disabled={busy||!ready} onClick={()=>send(null,prompts[key])} className={`stage ${session.stage===key?'active':''}`}><span className="stage-num">{n}</span><span><strong>{title}</strong><small>{sub}</small></span></button>)}</nav><div className="side-bottom"><div className="care-mark">Here for every mile.</div><p>From the first question to your next service, we’re here to help.</p><button className="reset" onClick={reset} disabled={busy}>＋ New conversation</button><small>Technical assessment · Fictional ABC Company</small></div></aside>
  <main><header><div><span className="eyebrow">CUSTOMER EXPERIENCE</span><h1>Your journey. One conversation.</h1></div><span className="mode"><i/>{health?.crmMode==='zoho'?'Zoho CRM':'Demo CRM'}</span></header>
   <div className="workspace"><section className="chat" aria-label="Customer chat"><div className="chat-top"><span className="avatar">A</span><div><strong>ABC Assistant</strong><small>{health?.llmMode==='groq'?'AI assistant · Groq':'Guided demo · No AI key required'}</small></div><span className="available">Here to help</span></div>
   <div className="messages" role="log" aria-live="polite" aria-relevant="additions text">
    <div className="intro"><span className="eyebrow">WELCOME ABOARD</span><h2>Where would you like<br/>to go today?</h2><p>Explore a vehicle, check your booking, or arrange your next service.</p><div className="suggestions"><button disabled={busy||!ready} onClick={()=>send(null,prompts.discovery)}>Explore the Thar ↗</button><button disabled={busy||!ready} onClick={()=>send(null,prompts.booking)}>Track a booking ↗</button></div></div>
    {session.messages.map((m,i)=><div key={i} className={`message ${m.role}`}><span className="speaker">{m.role==='user'?'YOU':'ABC ASSISTANT'}</span><div>{m.content}</div></div>)}
    {live&&<div className="message assistant"><span className="speaker">ABC ASSISTANT</span><div>{live}</div></div>}
    {busy&&<div className="thinking" role="status"><i/>{status||'Working on your request…'}</div>}
    {session.pending&&!busy&&<div className="review"><span className="eyebrow">REVIEW BEFORE SAVING</span><h3>{session.pending.kind==='lead'?'Register your interest':session.pending.kind==='service'?'Your service request':'Your follow-up preference'}</h3><dl>{Object.entries(session.pending.data).filter(([k])=>!['contactId','dealId'].includes(k)).map(([k,v])=><React.Fragment key={k}><dt>{readable(k)}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl><div className="review-actions"><button className="primary" onClick={()=>act('confirm')}>Confirm & save</button><button onClick={()=>act('cancel')}>Cancel</button></div></div>}
    <div ref={bottom}/></div>
    {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
    <form className="composer" onSubmit={send}><label className="sr-only" htmlFor="message">Your message</label><textarea id="message" ref={input} placeholder="Ask about a vehicle, booking, or service…" value={draft} maxLength={4000} disabled={!ready} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e);}}} rows={2}/><button className="send" type="submit" disabled={busy||!ready||!draft.trim()} aria-label="Send message">↑</button></form><div className="chat-foot">{health?.llmMode==='demo'?'Guided demo accepts labeled details: name: …; phone: …; city: …':'AI can make mistakes. Review your details before saving.'}</div>
   </section>
   <aside className="context"><div className="context-title"><h2>Your CRM details</h2><span className={`dot ${syncState==='Connected'?'online':''}`} title={syncState}/></div><p className="context-desc">Records connected to this conversation. Updates appear here as they arrive.</p><div className="sync"><span>{syncState}</span><button onClick={snapshot} disabled={!ready}>Refresh ↻</button></div>
    {!records.length&&<div className="empty"><span>◎</span><h3>A little context goes a long way.</h3><p>Your lead, booking, or service details will appear here after we find them.</p></div>}
    {records.map((item,i)=><article className="record" key={`${item.module}-${item.record?.id || i}`}><span className="record-type">{item.module}</span>{item.error?<p className="record-error">{item.error}</p>:<><h3>{item.record.name || item.record.fullName || item.record.subject || 'CRM record'}</h3><dl>{Object.entries(item.record).filter(([k,v])=>v!=null&&!['name','fullName','subject','contactId','modifiedAt','operationId'].includes(k)).map(([k,v])=><React.Fragment key={k}><dt>{readable(k)}</dt><dd>{k==='paymentUrl'?<a href={v} target="_blank" rel="noopener noreferrer">Open approved payment page ↗</a>:String(v)}</dd></React.Fragment>)}</dl></>}</article>)}
    {checked&&<small className="checked">Last checked {new Date(checked).toLocaleTimeString()}</small>}
    {health?.crmMode==='mock'&&<details className="demo-controls"><summary>Demo guide & CRM update</summary><p>All names, numbers, vehicle data and prices are fictional fixtures.</p><p>Deal: 9000000002<br/>Booking: MAH-9921<br/>Service contact: 9000000003</p><p>After looking up MAH-9921, change its allocation stage to demonstrate CRM → app sync.</p><label htmlFor="stage">Booking allocation</label><select id="stage" defaultValue="" onChange={async e=>{if(!e.target.value)return;try{await api('/demo/booking-stage',{method:'POST',body:JSON.stringify({stage:e.target.value})});}catch(err){setError(err.message);}}}><option value="" disabled>Select an update</option>{['Dispatch Pending','In Transit','Delivered'].map(v=><option key={v}>{v}</option>)}</select></details>}
    <div className="note">Vehicle details and prices use a synthetic assessment catalog. Confirm current specifications and final pricing with your dealer.</div>
   </aside></div><footer>ABC AUTOMOTIVE <span>Designed around your journey.</span></footer>
  </main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
